FROM alpine:latest
RUN apk update && apk add --no-cache git go

WORKDIR /app

RUN wget https://github.com/Vanilla-OS/Chronos/archive/refs/heads/main.zip && \
    unzip main.zip && \
    mv Chronos-main/* . && \
    rm -r Chronos-main main.zip

RUN go build -o chronos .

ENTRYPOINT ["./chronos"]
