name: Chronos Image
id: chronos
stages:
  - id: build
    base: ghcr.io/vanilla-os/pico:main
    singlelayer: false
    labels:
      maintainer: Vanilla OS Contributors
    entrypoint:
      exec:
        - /bin/sh
        - '-c'
        - cd /app && ./chronos
    args:
      DEBIAN_FRONTEND: noninteractive
    runs:
      commands:
        - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends
    modules:
      - name: update-repo
        type: shell
        commands:
          - apt-get update

      - name: install-deps
        type: apt
        source:
          packages:
            - git
            - nano
            - wget
      
      - name: install-go
        type: shell
        commands:
          - wget https://go.dev/dl/go1.24.0.linux-amd64.tar.gz
          - tar -C /usr/local -xzf go1.24.0.linux-amd64.tar.gz
          - /usr/local/go/bin/go version

      - name: build-app
        type: shell
        source:
          type: git
          url: https://github.com/Vanilla-OS/Chronos
          branch: main
          commit: latest
        commands:
          - mv /sources/build-app /app
          - cd /app
          - /usr/local/go/bin/go build -o chronos .
          - mv config /config
