name: Docker Image CI

on:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT"

      - name: Build the Docker image
        run: docker build . --file Containerfile --tag vanilla-os/chronos:test
